class MersenneRNG:
    def __init__(self, seed: int): ...
    def twist(self): ...
    def randint(self): ...
    def rand(self): ...
    def random_array(self, count: int): ...
    def randperm(self): ...
