class BlindedElement:
    @staticmethod
    def from_binary(data: bytes) -> "BlindedElement": ...
    def to_binary(self) -> bytes: ...

class EvaluationElement:
    @staticmethod
    def from_binary(data: bytes) -> "EvaluationElement": ...
    def to_binary(self) -> bytes: ...

class Proof:
    @staticmethod
    def from_binary(data: bytes) -> "Proof": ...
    def to_binary(self) -> bytes: ...

class PublicKey:
    @staticmethod
    def from_binary(data: bytes) -> "PublicKey": ...
    def to_binary(self) -> bytes: ...

class VoprfClient:
    @staticmethod
    def from_binary(data: bytes) -> "VoprfClient": ...
    def to_binary(self) -> bytes: ...

class VoprfServer:
    def __init__(self, server_seed: bytes) -> None: ...
    @staticmethod
    def derive_key(server_seed: bytes) -> bytes: ...
    def get_public_key(self) -> PublicKey: ...
    def batch_evaluate(self, inputs: list[bytes]) -> list[bytes]: ...
    def evaluate(self, input: bytes) -> bytes: ...
    def batch_blind_evaluate(self, messages: list[BlindedElement]) -> tuple[list[EvaluationElement], Proof]: ...

def prepare_batch_blind_inputs(inputs: list[bytes]) -> tuple[list[VoprfClient], list[BlindedElement]]:
    ...

def finalize_batch_blind_outputs(
    inputs: list[bytes], states: list[VoprfClient], messages: list[EvaluationElement], proof: Proof, public_key: PublicKey
) -> list[bytes]:
    ...
